export const openingsList = [
"3-gatsu no lion; 2; https://www.youtube.com/watch?v=ia_iUX2lyVk",
"3-gatsu no lion; 3; https://www.youtube.com/watch?v=qjf6jD_vI50",
"Akame ga Kill!; 1; https://www.youtube.com/watch?v=_Dptqf3Hbyw",
"Akame ga Kill!; 2; https://www.youtube.com/watch?v=YYIJJObcjM8",
"Aldonah.Zero; 2; https://www.youtube.com/watch?v=txiYc9FEUzY",
"Angel Beats!; 1; https://www.youtube.com/watch?v=-hA4na_3jT0",
"Another; 1; https://www.youtube.com/watch?v=kupW7eDG48s",
"Ansatsu Kyoushitsu; 4; https://www.youtube.com/watch?v=c_J7ybxenOQ",
"Ao Haru Ride; 1; https://www.youtube.com/watch?v=UccSonn2tT8",
"Ao no Exorcist; 1; https://www.youtube.com/watch?v=8gIFjsTcWoY",
"Ao no Exorcist; 2; https://www.youtube.com/watch?v=5ZPELMm-W68",
"Baki; 1; https://www.youtube.com/watch?v=eBKaURMSy7Y",
"Baki; 2; https://www.youtube.com/watch?v=SC4cUWuWeNw",
"Ballroom e Youkoso; 1; https://www.youtube.com/watch?v=EefNiVvWAB0",
"Ballroom e Youkoso; 2; https://www.youtube.com/watch?v=f-cAVbp1Oao",
"Black Bullet; 1; https://www.youtube.com/watch?v=as1Rz1KODXc",
"Black Clover; 1; https://www.youtube.com/watch?v=_6KZI74zKfE",
"Black Clover; 2; https://www.youtube.com/watch?v=5zSx8QD-fkA",
"Black Clover; 3; https://www.youtube.com/watch?v=LnATgmx7tGo",
"Black Clover; 4; https://www.youtube.com/watch?v=URwMxNidO-8",
"Black Clover; 5; https://www.youtube.com/watch?v=1YRBgrcaHdw",
"Black Clover; 6; https://www.youtube.com/watch?v=6edby9ExKOE",
"Black Clover; 7; https://www.youtube.com/watch?v=fFd1VkGc-SI",
"Black Rock Shooter; 1; https://www.youtube.com/watch?v=uEB_f5pbepA",
"Bleach; 1; https://www.youtube.com/watch?v=EFNQhmDLjTk",
"Bleach; 2; https://www.youtube.com/watch?v=92TEcszkRBw",
"Bleach; 3; https://www.youtube.com/watch?v=2edBgIH7y68",
"Bleach; 5; https://www.youtube.com/watch?v=YTMrvnyhMac",
"Bleach; 7; https://www.youtube.com/watch?v=OvahxFH7IGg",
"Bleach; 10; https://www.youtube.com/watch?v=b9vIpu0kAbE",
"Bleach; 12; https://www.youtube.com/watch?v=rUuHxyYqUSU",
"Bleach; 13; https://www.youtube.com/watch?v=XXjgwpayNoM",
"Bleach; 14; https://www.youtube.com/watch?v=NPRSvPFytPk",
"Bleach; 15; https://www.youtube.com/watch?v=pKf7YSXEBn4",
"Boku dake ga Inai Machi; 1; https://www.youtube.com/watch?v=Y9G20wV0KHE",
"Boku no Hero Academia; 1; https://www.youtube.com/watch?v=-77UEct0cZM",
"Boku no Hero Academia; 2; https://www.youtube.com/watch?v=Q7w5IMyJ3pM",
"Boku no Hero Academia; 3; https://www.youtube.com/watch?v=2ieT6Vh7jZE",
"Boku no Hero Academia; 4; https://www.youtube.com/watch?v=v1YojYU5nPQ",
"Boku no Hero Academia; 5; https://www.youtube.com/watch?v=W-d3kAf2NYw",
"Boogiepop wa Warawanai; 1; https://www.youtube.com/watch?v=ipXehesfNYI",
"Boruto; 1; https://www.youtube.com/watch?v=9prtl1aVcdM",
"Boruto; 2; https://www.youtube.com/watch?v=70WWSvrEoLs",
"Boruto; 4; https://www.youtube.com/watch?v=Xxk5gIW2r1Y",
"Btooom!; 1; https://www.youtube.com/watch?v=5GjbLOe_cgw",
"Bungou Stray Dogs; 1; https://www.youtube.com/watch?v=tvHqaimwcKE",
"Bungou Stray Dogs; 2; https://www.youtube.com/watch?v=v9OhNoPAZJY",
"Bungou Stray Dogs; 3; https://www.youtube.com/watch?v=fBC-ZCH_htA",
"Carole & Tuesday; 1; https://www.youtube.com/watch?v=jsNm1LQUrXM",
"Clannad After Story; 1; https://www.youtube.com/watch?v=hVMJxT3O9qA",
"Code Geass; 1; https://www.youtube.com/watch?v=cZ7zQbMxm28",
"Code Geass; 2; https://www.youtube.com/watch?v=YBhsDtFUgdM",
"Code Geass; 4; https://www.youtube.com/watch?v=bTU9RfI8WBk",
"Code Geass; 5; https://www.youtube.com/watch?v=mvFWDUhzrSo",
"Cowboy Bebop; 1; https://www.youtube.com/watch?v=NRI_8PUXx2A",
"Darker than Black; 3; https://www.youtube.com/watch?v=Tu-WyAn1zWg",
"Deadman Wonderland; 1; https://www.youtube.com/watch?v=Djn7jUL0Asc",
"Death Note; 1; https://www.youtube.com/watch?v=8QE9cmfxx4s",
"Death Note; 2; https://www.youtube.com/watch?v=d5HT8HoiAHg",
"Death Parade; 1; https://www.youtube.com/watch?v=UjjTMNDZi-A",
"Domestic na Kanojo; 1; https://www.youtube.com/watch?v=5WoZyCur8BM",
"Dororo; 1; https://www.youtube.com/watch?v=5DCGQ57ykME",
"Dororo; 2; https://www.youtube.com/watch?v=QZyK3uYq-qQ",
"Durarara!!; 1; https://www.youtube.com/watch?v=WNt8zC9zjEk",
"Elfen Lied; 1; https://www.youtube.com/watch?v=9JUoSGQYyGw",
"Fairy Tail; 3; https://www.youtube.com/watch?v=T60pzAKu60Q",
"Fairy Tail; 14; https://www.youtube.com/watch?v=vZ_Pw7Jos8M",
"Fairy Tail; 15; https://www.youtube.com/watch?v=aqRuzjIBkxY",
"Fairy Tail; 21; https://www.youtube.com/watch?v=b36-p0UryRw",
"Fairy Tail; 22; https://www.youtube.com/watch?v=e-7uuV7B7mo",
"Fairy Tail: Final Series; 1; https://www.youtube.com/watch?v=LKo-tk08zuM",
"Fate/Apocrypha; 1; https://www.youtube.com/watch?v=3nLH06ftkL0",
"Fate/Zero; 1; https://www.youtube.com/watch?v=BWGxSTLsrVo",
"Free!; 1; https://www.youtube.com/watch?v=JXkq0JWGMM8",
"Free!: Eternal Summer; 1; https://www.youtube.com/watch?v=umAWFigb91s",
"Free!: Dive to the Future; 1; https://www.youtube.com/watch?v=QyL14DeeJJs",
"Fullmetal Alchemist; 1; https://www.youtube.com/watch?v=Mu8vD7sxUgM",
"Fullmetal Alchemist; 4; https://www.youtube.com/watch?v=ORe7gt-mY14",
"Fullmetal Alchemist: Brotherhood; 1; https://www.youtube.com/watch?v=2uq34TeWEdQ",
"Fullmetal Alchemist: Brotherhood; 2; https://www.youtube.com/watch?v=iOsN2FP3-l4",
"Fullmetal Alchemist: Brotherhood; 3; https://www.youtube.com/watch?v=j3qHKeZjrdU",
"Fullmetal Alchemist: Brotherhood; 4; https://www.youtube.com/watch?v=KMZBauH47Jo",
"Fullmetal Alchemist: Brotherhood; 5; https://www.youtube.com/watch?v=cRA5gsdCf4c",
"Gamers!; 1; https://www.youtube.com/watch?v=DMKX9ETeJOw",
"Gangsta; 1; https://www.youtube.com/watch?v=cXb7M2DQiEk",
"Gekkan Shoujo Nozaki-kun; 1; https://www.youtube.com/watch?v=EjgOD9vruTE",
"Grand Blue; 1; https://www.youtube.com/watch?v=Mscy8evSJrs",
"Great Teacher Onizuka; 1; https://www.youtube.com/watch?v=phAoChN1nC4",
"Great Teacher Onizuka; 2; https://www.youtube.com/watch?v=LI6gNLwe4Mc",
"Grisaia no Rakuen; 2; https://www.youtube.com/watch?v=fABdDZBFJzs",
"Guilty Crown; 1; https://www.youtube.com/watch?v=DjUtmbZt8zc",
"Guilty Crown; 2; https://www.youtube.com/watch?v=Hv4znGv6lzg",
"Haikyuu!!; 1; https://www.youtube.com/watch?v=2---3Iysnqg",
"Haikyuu!!; 4; https://www.youtube.com/watch?v=as-sSVx3SmQ",
"Haikyuu!!; 5; https://www.youtube.com/watch?v=oRAF2-Exzx4",
"Hataraku Saibou; 1; https://www.youtube.com/watch?v=QYfdanAahVI",
"Hellsing; 1; https://www.youtube.com/watch?v=hMNJwUUHMxc",
"High School DxD BorN; 1; https://www.youtube.com/watch?v=ezwgEiYFP6A",
"Highschool of the Dead; 1; https://www.youtube.com/watch?v=TQwQMeb-44g",
"Hunter x Hunter; 1; https://www.youtube.com/watch?v=faqmNf_fZlE",
"Hyouka; 1; https://www.youtube.com/watch?v=Msuu3b-L-2k",
"Inuyashiki; 1; https://www.youtube.com/watch?v=5enNlA7ljvM",
"Isekai Shokudou; 1; https://www.youtube.com/watch?v=1y3p_bFoeQE",
"JoJo's Bizarre Adventure; 2; https://www.youtube.com/watch?v=6wDSFQFKSo0",
"JoJo's Bizarre Adventure; 9; https://www.youtube.com/watch?v=2eTlLDLsYB8",
"Joker Game; 1; https://www.youtube.com/watch?v=x5UGpOQH7P0",
"Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen; 1; https://www.youtube.com/watch?v=uKNiw5v9yGs",
"Kakegurui; 1; https://www.youtube.com/watch?v=Ce-yqZcRSHc",
"Kakeguruixx; 1; https://www.youtube.com/watch?v=KU3QM1pJffs",
"Kekkai Sensen; 1; https://www.youtube.com/watch?v=He6ZkZMS8VM",
"Keppeki Danshi! Aoyama-kun; 1; https://www.youtube.com/watch?v=E_T60A62WgI",
"Kill la Kill; 2; https://www.youtube.com/watch?v=qaLeO-2Fytg",
"Kimetsu no Yaiba; 1; https://www.youtube.com/watch?v=pmanD_s7G3U",
"Kiseijuu; 1; https://www.youtube.com/watch?v=4h6Mdhu8U-k",
"Bakemonogatari; 4; https://youtu.be/PiauQ7P7mtQ",
"Bakemonogatari; 5; https://youtu.be/d0X77h4H2bg",
"Nisemonogatari; 3; https://youtu.be/Y8SwZJAUiW4",
"Koi to Uso; 1; https://youtu.be/VrmzXR1sI78",
"Kuroko no Basket; 1; https://youtu.be/LIBPhMB4nZw",
"Kuroshitsuji; 1; https://youtu.be/ptxv3IxC8ZQ",
"Kuzu no Honkai; 1; https://youtu.be/0g-MG0JxxbE",
"Made in Abyss; 1; https://youtu.be/e91G8m9uM_0",
"Magi; 1; https://youtu.be/nGShsyMsfAg",
"Mahoutsukai no Yome; 1; https://youtu.be/KuZbmLLv1vM",
"Mekakucity Actors; 1; https://youtu.be/_1hNaDmBS-U",
"Mirai Nikki; 1; https://youtu.be/I59V9pjEOLI",
"Mirai Nikki; 2; https://youtu.be/7J-fy1nibzU",
"Mob psycho 100; 1; https://youtu.be/RU4qj0JDlek",
"Mob psycho 100; 2; https://youtu.be/epZaT8B31-g",
"Monster; 1; https://youtu.be/msTB5r8nUHU",
"Nanatsu no Taizai; 1; https://youtu.be/8UbS2pKIyOQ",
"Nanatsu no Taizai; 2; https://youtu.be/WK-EUELKb9A",
"Nanatsu no Taizai; 3; https://youtu.be/kAg5PKPSQ3c",
"Nanatsu no Taizai; 4; https://youtu.be/4QkEZl34wCo",
"Naruto; 1; https://youtu.be/4t__wczfpRI",
"Naruto; 2; https://youtu.be/SRn99oN1p_c",
"Naruto; 3; https://youtu.be/FQIpIDLcg1Q",
"Naruto; 4; https://youtu.be/eRh6GFQB3Ks",
"Naruto; 5; https://youtu.be/wCI9SuOT6qk",
"Naruto; 7; https://youtu.be/pY15k20Hqq0",
"Naruto; 8; https://youtu.be/yB2g22359Fg",
"Naruto; 9; https://youtu.be/-m8kR0FQ7Wk",
"Naruto Shippuden; 1; https://youtu.be/YsWTD6Pk-S8",
"Naruto Shippuden; 2; https://youtu.be/eWNNjIIq4TA",
"Naruto Shippuden; 3; https://www.youtube.com/watch?v=KruXhNuindw&list=PLxsWPuOO4owZdHn71EeyCZLEO71swbjCg&index=205&t=0s",
"Naruto Shippuden; 4; https://www.youtube.com/watch?v=p3zK28YYI-4&list=PLxsWPuOO4owZdHn71EeyCZLEO71swbjCg&index=206&t=12s",
"Naruto Shippuden; 5; https://www.youtube.com/watch?v=yCPoUk19kvE&list=PLxsWPuOO4owZdHn71EeyCZLEO71swbjCg&index=207&t=14s",
"Naruto Shippuden; 6; https://www.youtube.com/watch?v=SavhHnWla6c&t=13s",
"Naruto Shippuden; 7; https://www.youtube.com/watch?v=lGTp4VogNaQ&t=14s",
"Naruto Shippuden; 9; https://www.youtube.com/watch?v=KmrTuNXVrf4",
"Naruto Shippuden; 8; https://www.youtube.com/watch?v=kTfTY6kGAao",
"Naruto Shippuden; 10; https://www.youtube.com/watch?v=JDJDtBofuTQ",
"Naruto Shippuden; 13; https://www.youtube.com/watch?v=lywb69Cn41g",
"Naruto Shippuden; 16; https://www.youtube.com/watch?v=LDDWf1vu9gA&list=PLxsWPuOO4owZdHn71EeyCZLEO71swbjCg&index=212&t=0s",
"Naruto Shippuden; 19; https://www.youtube.com/watch?v=d08dw3ztKZw&list=PLxsWPuOO4owZdHn71EeyCZLEO71swbjCg&index=213&t=11s",
"No Game No Life; 1; https://youtu.be/NQCax11Q0Bs",
"Noragami; 1; https://youtu.be/gWCnKoEgfP0",
"Noragami; 2; https://youtu.be/aZenmeRytEM",
"One Punch Man; 1; https://youtu.be/atxYe-nOa9w",
"One Punch Man; 2; https://youtu.be/rIK39VOoezs",
"Ookami to Koushinryou; 1; https://youtu.be/oPAF4nlFZrE",
"Ore Monogatari; 1; https://youtu.be/_1x1wXwfFqU",
"Overlord; 1; https://youtu.be/KOWcj7XKnfQ",
"Overlord; 2; https://youtu.be/4DpKM9AG2n0",
"Overlord; 3; https://youtu.be/S9yfM5OrpKU",
"Owari No Seraph; 1; https://youtu.be/MxoJvOE7hcU",
"Persona 5 The Animation; 1; https://youtu.be/k-XHBUganUs",
"Prison School; 1; https://youtu.be/T1ufKG_UR8Y",
"Re:Zero; 1; https://youtu.be/0Vwwr3VGsYg",
"Re:Zero; 2; https://youtu.be/iu_0kOfMGD0",
"Rokudenashi Majutsu Koushi to Akashic Records; 1; https://youtu.be/TYCIdFby_90",
"Sakamoto Desu Ga?; 1; https://youtu.be/f8d3bW42aFY",
"Samurai Champloo; 1; https://youtu.be/Eq6EYcpWB_c",
"Shigatsu wa kimi no uso; 1; https://youtu.be/2Ex3bu6CxPU",
"Shigatsu wa kimi no uso; 2; https://youtu.be/aARAM5YTAso",
"Shingeki no Bahamut: Virgin Soul; 1; https://youtu.be/VR3uKfIhkQ4",
"Shingeki no Bahamut: Virgin Soul; 2; https://youtu.be/YOLE_WCYKZQ",
"Shingeki no Kyojin; 1; https://youtu.be/XMXgHfHxKVM",
"Shingeki no Kyojin; 2; https://youtu.be/PbWFpzi8C94",
"Shingeki no Kyojin; 3; https://youtu.be/CID-sYQNCew",
"Shingeki no Kyojin; 4; https://youtu.be/NoS02YodYt8",
"Shingeki no Kyojin; 5; https://youtu.be/0dK7JgKivQM",
"Shokugeki no Souma; 1; https://youtu.be/0dK7JgKivQM ",
"Shokugeki no Souma; 2; https://youtu.be/vm6R8MgqR9A",
"Shokugeki no Souma; 3; https://www.youtube.com/watch?v=dWlBTmKhZVo",
"Shokugeki no Souma; 4; https://youtu.be/jiEGfig5knE",
"Shokugeki no Souma; 5; https://youtu.be/ZvNGzlLlSOM",
"Soul Eater; 1; https://youtu.be/zzJ8U8OtEsE",
"Steins Gate; 1; https://youtu.be/dd7BILZcYAY",
"Steins Gate 0; 1; https://youtu.be/1xJbdY9B3A8",
"Subete ga F ni Naru; 1; https://youtu.be/iY7mrXEc498",
"Sword Art Online; 1; https://youtu.be/OsLY7DXWsF4",
"Sword Art Online; 2; https://youtu.be/gAi4PwjTfRU",
"Sword Art Online; 3; https://youtu.be/1EIbMbidkj4",
"Sword Art Online; 4; https://youtu.be/Om9G2D4h0Jw",
"Sword Art Online; 5; https://youtu.be/6qe6uPzsecE; Alterinative Gun Gale",
"Sword Art Online; 6; https://youtu.be/zKdI7D2O3ac; Catch the moment",
"Sword Art Online; 7; https://youtu.be/i_Y-GwM6o5M; Adamas",
"Tate no Yuusha no Nariagari; 1; https://youtu.be/jZvFEtR8RH0",
"Tate no Yuusha no Nariagari; 2; https://youtu.be/jZvFEtR8RH0",
"Tengen Toppa Gurren Lagann; 1;  https://youtu.be/b5hZiuOUdXw",
"Tokyo Ghoul; 1; https://youtu.be/uMeR2W19wT0",
"Tokyo Ghoul; 2; https://youtu.be/ccBOtOcE-gU",
"Tokyo Ghoul; 3; https://youtu.be/ZCCG3oQKu90",
"Toradora!; 1; https://youtu.be/Y3Xmzu0OtS8",
"Trinity Seven; 2; https://www.youtube.com/watch?v=RsLyrdv_18c; movie",
"Violet Evergarden; 1; https://youtu.be/mtuwpsc8KKI",
"Wotaku ni Koi wa Muzukashii; 1; https://www.youtube.com/watch?v=qHNUEyCb564&t=2s",
"Yakusoku no Neverland; 1; https://youtu.be/1JoFsTDfd-8",
"Youjo Senki; 1; https://youtu.be/4S6e542qEm0",
"Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e; 1; https://youtu.be/kMBaVZqUXYY",
"Yuri!!! on Ice; 1; https://youtu.be/ORDXWrL5EuQ",
"Yu Yu Hakusho; 2; https://www.youtube.com/watch?v=2l9V2ejc6OY",
"Zetsuen no Tempest; 1; https://youtu.be/YtNMIbQPzCY",
"Fate/Apocrypha; 2; https://youtu.be/DF38s43Qywc",
"Hai to Gensou no Grimgar; 1; https://youtu.be/-rIE7Qr4J0U",
"Kokkoku; 1; https://www.youtube.com/watch?v=fhBA6ynorvc",
"Anohana; 1; https://youtu.be/4HHcnKgOyTQ",
"Log Horizon; 2; https://youtu.be/CZ73Qv-RQNg",
"Fairy Tail 2018; 3; https://youtu.be/YAi8K_5pHWA",
"Pokemon XYZ; 1; https://www.youtube.com/watch?v=CQuObfTx6Cg",
"Pokemon; 1; https://www.youtube.com/watch?v=6xKWiCMKKJg",
"Yu-Gi-Oh! GX; 2; https://www.youtube.com/watch?v=a8246R_OsdA",
"Yu-Gi-Oh!; 1; https://www.youtube.com/watch?v=WHUcHw7j2Mc",
"Neon Genesis Evangelion; 1; https://www.youtube.com/watch?v=t-QSmNReDyI",
"Goblin Slayer; 1; https://www.youtube.com/watch?v=3SWgludvJcw",
"Trigun; 1; https://www.youtube.com/watch?v=4OxFSy8G5wk",
"Inuyasha; 1; https://www.youtube.com/watch?v=KwCfHVGamn8",
"Plastic Memories; 1; https://youtu.be/IKyIXiTLJc4",
"Blend S; 1; https://youtu.be/dv7MYtlnNus",
"Gate; 2; https://www.youtube.com/watch?v=pl1sTU2MANU",
"Little Witch Academia; 1; https://www.youtube.com/watch?v=JRmgL564x8E",
"Yamada-kun to 7-nin no Majo; 1; https://www.youtube.com/watch?v=QHFif7LRylw",
"Yuru Camp; 1; https://www.youtube.com/watch?v=sM-yk4AmTzo",
"Fairy Gone; 1; https://www.youtube.com/watch?v=bcewsha-zvI",
"Re: Creators; 1; https://www.youtube.com/watch?v=MEEVGqvvXbI",
"Konosuba; 2; https://www.youtube.com/watch?v=VtfUrDwpo2E",
"Nanbaka; 1; https://www.youtube.com/watch?v=RKz5ty-0zgI",
"Divine Gate; 1; https://www.youtube.com/watch?v=aYZrGPXQX40",
"Taboo Tattoo; 1; https://www.youtube.com/watch?v=N1vkUkgIkl8",
"Acca 13; 1; https://www.youtube.com/watch?v=pITNm95Sd1k",
"Tales of Zestiria The X; 1; https://www.youtube.com/watch?v=9vjsu3Lb9Co",
"Dragon Ball Super; 2; https://www.youtube.com/watch?v=Li76Oh-HdIw",
"Durarara!! X2 Ketsu; 1; https://www.youtube.com/watch?v=DPtFrCODF2I",
"Princess Principal; 1; https://www.youtube.com/watch?v=8QjqkATvH9M",
"Gintama; 21; https://www.youtube.com/watch?v=s5Tyx2B5er0",
"Hamatora; 2; https://www.youtube.com/watch?v=f74_M9-o9do",
"Shakugan no Shana; 1; https://www.youtube.com/watch?v=YqL4VQr2EJc",
"Shakugan no Shana; 3; https://www.youtube.com/watch?v=z3LB2MMd6-A",
"Darker Than Black Ryuusei no Gemini; 1; https://www.youtube.com/watch?v=Myytcopk-DA",
"Baccano!; 1; https://www.youtube.com/watch?v=OOZ1hsb8smQ",
"Watamote; 1; https://www.youtube.com/watch?v=gZYq7rat9d4",
"Dragon Ball Z; 1; https://www.youtube.com/watch?v=GHnfX1RmZX8",
"Berserk 2016; 1; https://www.youtube.com/watch?v=q2SWV5xxtcQ",
"Gintama; 13; https://www.youtube.com/watch?v=iXpGVuaQwXo",
"Enen no Shouboutai; 1; https://www.youtube.com/watch?v=ha-l5oFADVc",
"Vinland Saga; 1; https://www.youtube.com/watch?v=xEVcTStgA4A",
];